spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/nms_db
    username: nms_user
    password: nms_user

server:
  port: 8080

logging:
  level:
    org.apache.ibatis: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.network.nms.domain
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: C5fxvkTIhV+zO+dUJHhzE48Pu5MOqjbC/pFO0L3XRbXfWC6P2+UX+slNwXWXXVm3
  expiration: 3600000 # 1시간